apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: 21stcenturycloudsolutions-tls
spec:
  secretName: 21stcenturycloudsolutions-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: 21stcenturycloudsolutions.com
  dnsNames:
    - 21stcenturycloudsolutions.com
    - www.21stcenturycloudsolutions.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - 21stcenturycloudsolutions.com
          - www.21stcenturycloudsolutions.com
